drop table if exists comb_data;

create table comb_data
(Organisation VARCHAR(63),
Account_ID INT,
Child_ID INT,
Status VARCHAR(15),
Child_DOB DATE,
School_Year INT,
Age INT,
Gender VARCHAR(7),
Profile_ID INT,
Completed_Date DATETIME,
Profile_Type VARCHAR(15),
Dev_Stage VARCHAR(63),
Being_Special INT,
Having_Needs_Met INT,
Being_Safe INT,
Explore_Safely INT,
Exploring_and_Experimenting INT,
Experiencing_Options INT,
Expressing_a_view INT,
Learning_about_Cause_and_Effect INT,
Feeling_Thinking_and_Problem_solving INT,
Developing_an_identity INT,
Fantasy_and_Reality INT,
Power_with_Responsibility INT,
Motivation_for_Developing_Skills INT,
Morals_and_Values INT,
Understanding_the_need_for_Rules INT,
Establishing_Independence INT,
Connecting_with_Peers INT,
Exploring_Identity_and_Gender INT,
Initiating_Engaging_and_Doing INT,
Overall_Score INT);

